import { type DBSchema, type IDBPDatabase, openDB } from "idb";
import { identifyProject } from "$/modules/project/logic/project-info";
import type { TTMLLyric } from "$/types/ttml";

const DB_NAME = "amll-autosave-db";
const DB_VERSION = 3;

/**
 * @description Legacy snapshot structure, used for data migration only
 * @internal
 */
interface LegacySnapshot {
	id?: number;
	timestamp: number;
	lyrics: TTMLLyric;
}

/**
 * @description Basic project information, used to quickly restore the latest version
 */
export interface ProjectInfo {
	/**
	 * @description Unique project identifier
	 */
	id: string;
	/**
	 * @description Project display name, typically generated by `identifyProject`
	 */
	name: string;
	/**
	 * @description Last modified timestamp
	 */
	lastModified: number;
	/**
	 * @description Lyric preview text
	 */
	preview?: string;
	/**
	 * @description Latest version of the project
	 */
	latestState: TTMLLyric;
	/**
	 * @description Saved file name of the project
	 */
	saveFileName?: string;
	/**
	 * @description Associated audio file name
	 */
	audioFileName?: string | null;
	/**
	 * @description Associated audio file absolute path (Tauri desktop)
	 */
	audioPath?: string | null;
}

/**
 * @description Historical version of the project
 */
export interface ProjectVersion {
	/**
	 * @description Auto-increment primary key ID
	 */
	id?: number;
	/**
	 * @description Associated project ID (foreign key)
	 *
	 */
	projectId: string;
	/**
	 * @description Timestamp when saved
	 */
	timestamp: number;
	/**
	 * @description Lyric data for this version
	 */
	data: TTMLLyric;
	/**
	 * @description File name when saved
	 */
	saveFileName?: string;
	/**
	 * @description Associated audio file name
	 */
	audioFileName?: string | null;
	/**
	 * @description Associated audio file absolute path
	 */
	audioPath?: string | null;
}

export interface AudioCacheEntry {
	id: string;
	projectId?: string;
	fileName: string;
	path?: string;
	blob: Blob;
	timestamp: number;
	isAutoDownloaded?: boolean;
}

/**
 * @description Database Schema definition
 */
interface AutosaveDBSchema extends DBSchema {
	/**
	 * @description Stores metadata (latest only) and state for each project
	 */
	projects: {
		key: string;
		value: ProjectInfo;
		indexes: { "by-last-modified": number };
	};
	/**
	 * @description Stores history records for all projects
	 */
	versions: {
		key: number;
		value: ProjectVersion;
		indexes: {
			/**
			 * @description Used to query all versions of a project
			 */
			"by-project": string;
			/**
			 * @description Used to query the latest version of a project
			 */
			"by-project-date": [string, number];
		};
	};
	audio_cache: {
		key: string;
		value: AudioCacheEntry;
		indexes: {
			"by-project": string;
			"by-filename": string;
		};
	};
}

let dbPromise: Promise<IDBPDatabase<AutosaveDBSchema>> | null = null;

/**
 * @description Get database instance
 */
function getDB() {
	if (!dbPromise) {
		dbPromise = openDB<AutosaveDBSchema>(DB_NAME, DB_VERSION, {
			async upgrade(db, oldVersion, _newVersion, transaction) {
				if (!db.objectStoreNames.contains("projects")) {
					const projectStore = db.createObjectStore("projects", {
						keyPath: "id",
					});
					projectStore.createIndex("by-last-modified", "lastModified");
				}

				if (!db.objectStoreNames.contains("versions")) {
					const versionStore = db.createObjectStore("versions", {
						keyPath: "id",
						autoIncrement: true,
					});
					versionStore.createIndex("by-project", "projectId");
					versionStore.createIndex("by-project-date", [
						"projectId",
						"timestamp",
					]);
				}

				if (!db.objectStoreNames.contains("audio_cache")) {
					const audioStore = db.createObjectStore("audio_cache", {
						keyPath: "id",
					});
					audioStore.createIndex("by-project", "projectId");
					audioStore.createIndex("by-filename", "fileName");
				}

				if (
					oldVersion < 2 &&
					// biome-ignore lint/suspicious/noExplicitAny: Legacy snapshot
					db.objectStoreNames.contains("snapshots" as any)
				) {
					const legacyProjectId = "legacy_autosave_archive";
					// biome-ignore lint/suspicious/noExplicitAny: Legacy snapshot, should exist
					const oldStore = transaction.objectStore("snapshots" as any);
					const oldSnapshots = (await oldStore.getAll()) as LegacySnapshot[];

					if (oldSnapshots && oldSnapshots.length > 0) {
						oldSnapshots.sort((a, b) => a.timestamp - b.timestamp);
						const latestSnapshot = oldSnapshots[oldSnapshots.length - 1];
						const projectStore = transaction.objectStore("projects");
						await projectStore.put({
							id: legacyProjectId,
							name: "Legacy Snapshots Archive",
							lastModified: latestSnapshot.timestamp,
							latestState: latestSnapshot.lyrics,
							preview: "(History from legacy autosave)",
						});
						const versionStore = transaction.objectStore("versions");
						for (const snap of oldSnapshots) {
							await versionStore.add({
								projectId: legacyProjectId,
								timestamp: snap.timestamp,
								data: snap.lyrics,
							});
						}
					}
					// biome-ignore lint/suspicious/noExplicitAny: Legacy snapshot, should exist
					db.deleteObjectStore("snapshots" as any);
				}
			},
		});
	}
	return dbPromise;
}

export interface AutoSaveExtraOptions {
	saveFileName?: string;
	audioFileName?: string | null;
	audioPath?: string | null;
	audioBlob?: Blob | null;
}

/**
 * @description Execute autosave operation
 * @param projectId Project ID for the current session
 * @param lyrics Lyric data currently in the editor
 * @param limit Maximum number of historical versions to keep per project
 * @param saveInterval Interval threshold for creating historical versions (ms)
 * @param options Optional parameters including saveFileName, audioFileName, audioPath, and audioBlob
 */
export async function autoSaveProject(
	projectId: string,
	lyrics: TTMLLyric,
	limit: number,
	saveInterval: number,
	options?: AutoSaveExtraOptions,
) {
	const db = await getDB();

	const identity = identifyProject(lyrics);
	const now = Date.now();

	const tx = db.transaction(["projects", "versions"], "readwrite");
	const projectStore = tx.objectStore("projects");
	const versionStore = tx.objectStore("versions");

	const existingProject = await projectStore.get(projectId);
	const saveFileName = options?.saveFileName || existingProject?.saveFileName;
	const audioFileName =
		options?.audioFileName !== undefined
			? options.audioFileName
			: (existingProject?.audioFileName ?? null);
	const audioPath =
		options?.audioPath !== undefined
			? options.audioPath
			: (existingProject?.audioPath ?? null);

	await projectStore.put({
		id: projectId,
		name: identity.displayName,
		lastModified: now,
		latestState: lyrics,
		preview: lyrics.lyricLines[0]?.words.map((w) => w.word).join("") || "",
		saveFileName,
		audioFileName,
		audioPath,
	});

	let lastVersionTime = 0;
	const index = versionStore.index("by-project-date");
	const range = IDBKeyRange.bound([projectId, 0], [projectId, Infinity]);
	const cursor = await index.openCursor(range, "prev");

	if (cursor) {
		lastVersionTime = cursor.value.timestamp;
	}

	if (now - lastVersionTime > saveInterval) {
		await versionStore.add({
			projectId: projectId,
			timestamp: now,
			data: lyrics,
			saveFileName,
			audioFileName,
			audioPath,
		});

		const allVersionKeys = await index.getAllKeys(range);
		if (allVersionKeys.length > limit) {
			const keysToDelete = allVersionKeys.slice(
				0,
				allVersionKeys.length - limit,
			);
			await Promise.all(keysToDelete.map((key) => versionStore.delete(key)));
		}
	}

	await tx.done;

	if (options?.audioBlob && options.audioBlob.size > 0) {
		await saveAudioToCache({
			projectId,
			fileName: audioFileName || "audio",
			path: audioPath,
			blob: options.audioBlob,
		});
	}
}

/**
 * @description Cache audio to IndexedDB
 */
export async function saveAudioToCache(entry: {
	projectId?: string;
	fileName: string;
	path?: string | null;
	blob: Blob;
	isAutoDownloaded?: boolean;
}) {
	try {
		const db = await getDB();
		const id = entry.projectId || entry.fileName;
		const isAuto =
			entry.isAutoDownloaded ??
			(entry.blob as any).isAutoDownloaded ??
			false;
		await db.put("audio_cache", {
			id,
			projectId: entry.projectId,
			fileName: entry.fileName,
			path: entry.path || undefined,
			blob: entry.blob,
			timestamp: Date.now(),
			isAutoDownloaded: isAuto,
		});
	} catch (e) {
		console.warn("Failed to cache audio in IndexedDB:", e);
	}
}

/**
 * @description Retrieve cached audio from IndexedDB
 */
export async function getAudioFromCache(
	projectId?: string,
	fileName?: string,
): Promise<AudioCacheEntry | null> {
	try {
		const db = await getDB();
		if (projectId) {
			const byId = await db.get("audio_cache", projectId);
			if (byId) return byId;
			const byProject = await db.getFromIndex(
				"audio_cache",
				"by-project",
				projectId,
			);
			if (byProject) return byProject;
		}
		if (fileName) {
			const byId = await db.get("audio_cache", fileName);
			if (byId) return byId;
			const byFileName = await db.getFromIndex(
				"audio_cache",
				"by-filename",
				fileName,
			);
			if (byFileName) return byFileName;
		}
	} catch (e) {
		console.warn("Failed to get audio from cache:", e);
	}
	return null;
}

/**
 * @description Get list of all projects
 * @returns Project list, most recent first
 */
export async function getProjectList(): Promise<ProjectInfo[]> {
	const db = await getDB();
	const projects = await db.getAllFromIndex("projects", "by-last-modified");
	return projects.reverse();
}

/**
 * @description Get all historical versions of a project
 * @param projectId Project ID
 * @returns List of versions, most recent first
 */
export async function getProjectVersions(
	projectId: string,
): Promise<ProjectVersion[]> {
	const db = await getDB();
	const range = IDBKeyRange.bound([projectId, 0], [projectId, Infinity]);
	const versions = await db.getAllFromIndex(
		"versions",
		"by-project-date",
		range,
	);
	return versions.reverse();
}

/**
 * @description Get latest state of a specified project
 * @param projectId ID of the project to retrieve
 */
export async function getProjectLatestState(
	projectId: string,
): Promise<TTMLLyric | undefined> {
	const db = await getDB();
	const project = await db.get("projects", projectId);
	return project?.latestState;
}

/**
 * @description Export all projects and versions for backup
 * @returns All project info and historical versions
 */
export async function exportAllProjectsData(): Promise<{
	projects: ProjectInfo[];
	versions: ProjectVersion[];
}> {
	const db = await getDB();
	const [projects, versions] = await Promise.all([
		db.getAll("projects"),
		db.getAll("versions"),
	]);
	return { projects, versions };
}

/**
 * @description Restore project data from backup. Existing projects will be upserted
 * and their historical versions completely replaced; projects not in backup remain unchanged.
 * @param projects Project info to restore
 * @param versions Historical versions to restore (excluding auto-increment primary key, reassigned by DB)
 */
export async function restoreProjectsData(
	projects: ProjectInfo[],
	versions: Omit<ProjectVersion, "id">[],
): Promise<void> {
	const db = await getDB();
	const tx = db.transaction(["projects", "versions"], "readwrite");
	const projectStore = tx.objectStore("projects");
	const versionStore = tx.objectStore("versions");
	const versionIndex = versionStore.index("by-project");

	for (const project of projects) {
		await projectStore.put(project);
		const existingKeys = await versionIndex.getAllKeys(project.id);
		await Promise.all(existingKeys.map((key) => versionStore.delete(key)));
	}

	for (const version of versions) {
		const { id: _ignored, ...rest } = version as ProjectVersion;
		await versionStore.add(rest);
	}

	await tx.done;
}

/**
 * @description Delete a project and all of its history records
 * @param projectId ID of the project to delete
 */
export async function deleteProject(projectId: string): Promise<void> {
	const db = await getDB();
	const tx = db.transaction(["projects", "versions"], "readwrite");
	await tx.objectStore("projects").delete(projectId);

	const versionStore = tx.objectStore("versions");
	const index = versionStore.index("by-project");
	const keys = await index.getAllKeys(projectId);

	await Promise.all(keys.map((k) => versionStore.delete(k)));

	await tx.done;
}
