"$schema" = "../gen/schemas/desktop-schema.json"
identifier = "default"
description = "enables the default permissions"
windows = ["*"]

[[permissions]]
identifier = "core:default"
[[permissions]]
identifier = "os:default"
[[permissions]]
identifier = "os:allow-os-type"
[[permissions]]
identifier = "core:window:default"
[[permissions]]
identifier = "core:window:allow-start-dragging"
[[permissions]]
identifier = "core:window:allow-toggle-maximize"
[[permissions]]
identifier = "core:window:allow-minimize"
[[permissions]]
identifier = "core:window:allow-show"
[[permissions]]
identifier = "core:window:allow-close"
[[permissions]]
identifier = "core:window:allow-set-focus"
[[permissions]]
identifier = "core:window:allow-maximize"
[[permissions]]
identifier = "core:window:allow-unmaximize"
[[permissions]]
identifier = "core:window:allow-set-effects"
[[permissions]]
identifier = "decorum:allow-show-snap-overlay"
[[permissions]]
identifier = "shell:allow-open"

[[permissions]]
identifier = "shell:allow-execute"

[[permissions]]
identifier = "updater:default"

[[permissions]]
identifier = "log:default"

[[permissions]]
identifier = "dialog:default"

[[permissions]]
identifier = "fs:default"

[[permissions]]
identifier = "fs:read-files"

[[permissions]]
identifier = "fs:write-files"

[[permissions]]
identifier = "fs:allow-read"

[[permissions]]
identifier = "fs:allow-read-file"

[[permissions]]
identifier = "fs:allow-write"

[[permissions]]
identifier = "fs:allow-write-file"

[[permissions]]
identifier = "fs:allow-write-text-file"

[[permissions]]
identifier = "fs:allow-exists"

[[permissions]]
identifier = "fs:allow-stat"


